name: Build and Release Executable

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (required)'
        required: true
        default: 'v.0.0.1'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Verify PyInstaller installation
        run: pyinstaller --version

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --hidden-import=pypresence --hidden-import=requests --hidden-import=dotenv main.py

      - name: Rename executable
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv dist/main.exe dist/windows-${{ github.event.inputs.version }}.exe
          else
            mv dist/main dist/linux-${{ github.event.inputs.version }}
            chmod +x dist/linux-${{ github.event.inputs.version }}
          fi
        shell: bash

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-${{ matrix.os }}
          path: dist/main-${{ matrix.os }}*

      - name: Create and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ github.event.inputs.version }} ${{ github.sha }}
          git push origin ${{ github.event.inputs.version }}

      - name: Upload executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main-${{ matrix.os }}*
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
