name: Build and Release Executable

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (required)'
        required: true
        default: 'v.0.0.1'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Install UPX
        run: sudo apt-get install -y upx

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'main.py'
          requirements: 'requirements.txt'
          options: --onefile --upx-dir /usr/bin
          upload_exe_with_name: 'executable-${{ matrix.os }}-${{ github.event.inputs.version }}'

      - name: Create and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ github.event.inputs.version }} ${{ github.sha }}
          git push origin ${{ github.event.inputs.version }}

      - name: Upload executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
